#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5871-webs
    bind *:80
    mode http
    balance roundrobin
    server 5871-web-01 54.163.21.182:80 check
    server 5871-web-02 34.224.102.65:80  check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
