#!/usr/bin/env bash
# Install nginx web server, and return a page when querying Nginx

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Ensure Nginx is listening on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx without using systemctl
sudo kill -s HUP $(cat /var/run/nginx.pid)

# Create a default HTML page with the required string
echo "Holberton School" | sudo tee /var/www/html/index.html

# Script execution complete
sudo service nginx start
