#!/usr/bin/env bash
# Install Nginx using Homebrew
brew install nginx

# Create necessary directories
sudo mkdir -p /usr/local/var/www/html

# Create the HTML file
sudo bash -c 'echo "Holberton School" > /usr/local/var/www/html/index.html'

# Start Nginx service
brew services start nginx
